{{- if .Values.o11yHub.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "signoz.serviceAccountName" . }}
  labels:
    {{- include "signoz.labels" . | nindent 4 }}
  {{- with .Values.o11yHub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "signoz.imagePullSecrets" . }}
{{- end -}}
