{{- if and .Values.otelCollector.tls.enabled (not .Values.otelCollector.tls.existingSecretName) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "otelCollector.fullname" . }}-tls
  namespace: {{ include "signoz.namespace" . }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.otelCollector.tls.certificate | b64enc }}
  tls.key: {{ .Values.otelCollector.tls.key | b64enc }}
  {{- if .Values.otelCollector.tls.ca }}
  ca.crt: {{ .Values.otelCollector.tls.ca | b64enc }}
  {{- end }}
{{- end }}